feat(cd): added app readiness check in deployment workflow

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -85,3 +85,17 @@ jobs:
             docker compose up -d --no-deps --force-recreate nginx
             docker compose ps
           EOF
+
+      - name: Wait for app to be ready
+        run: |
+          for i in {1..15}; do
+            if curl -sf https://${{ secrets.APP_DOMAIN }}/health; then
+              echo "App is ready"
+              exit 0
+            fi
+            echo "Waiting..."
+            sleep 5
+          done
+
+          echo "App failed to start"
+          exit 1
